name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 运行
  workflow_dispatch:

permissions:
  contents: write  # 允许修改 README

jobs:
  update-readme:
    name: Update README with WakaTime Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Waka Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 用默认 token 即可
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_DAYS_OF_WEEK: "True"

      # 可选调试
      - name: Debug log
        if: failure()
        run: |
          echo "Workflow failed, printing debug info..."
          ls -la
